image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/artifacts/app-ibank.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true  --info